all:

%:
	@echo "-----------"
	@echo ""
	@echo "GNU Make is not supported with the Makefile included in 0x58-unix please use a BSD compatible make!"
	@echo ""
	@echo "-----------"
	@echo ""
	@bsdmake -j 4 $@
